//! AR-ACE proof-off-path execution.
//!
//! This instruction accepts a relay attestation instead of a full ZK proof.
//! The attestation proves that a registered relay node vouches for the
//! transaction. Full validity is deferred to the aggregated STARK proof
//! generated by the builder.
//!
//! Flow:
//! 1. User signs Attest = Ed25519.Sign(sk_relay, objHash || domain || nonce)
//! 2. Relay verifies Attest, forwards (tx, Attest)
//! 3. This instruction verifies the attestation on-chain
//! 4. Builder later generates aggregated STARK via verify_aggregated

use anchor_lang::prelude::*;
use anchor_lang::solana_program::hash::hash as sha256_hash;
use crate::errors::SolaaError;
use crate::state::{SolaaAccount, RelayRegistry};
use crate::verifier::attestation::{verify_attestation, is_relay_authorized};

#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct ExecuteAttestedArgs {
    /// The original id_com used as the PDA seed (frozen at initialization).
    pub seed_id_com: [u8; 32],
    /// The transaction payload.
    pub payload: Vec<u8>,
    /// Ed25519 signature over (obj_hash || domain || nonce).
    pub signature: [u8; 64],
    /// Ed25519 public key of the attesting relay node.
    pub relay_pubkey: [u8; 32],
    /// Hash of the object being attested (typically SHA-256(payload)).
    pub obj_hash: [u8; 32],
    /// Chain domain tag.
    pub domain: u64,
    /// Attestation nonce (for replay prevention).
    pub attest_nonce: u64,
}

#[derive(Accounts)]
#[instruction(args: ExecuteAttestedArgs)]
pub struct ExecuteAttested<'info> {
    #[account(
        mut,
        seeds = [SolaaAccount::SEED_PREFIX, args.seed_id_com.as_ref()],
        bump = smart_account.bump,
    )]
    pub smart_account: Account<'info, SolaaAccount>,

    #[account(seeds = [RelayRegistry::SEED_PREFIX], bump = relay_registry.bump)]
    pub relay_registry: Account<'info, RelayRegistry>,

    /// Anyone can submit — authorization comes from the attestation.
    pub submitter: Signer<'info>,

    /// Instructions sysvar for Ed25519 signature verification via introspection.
    /// CHECK: verified via address constraint.
    #[account(address = anchor_lang::solana_program::sysvar::instructions::ID)]
    pub instructions: AccountInfo<'info>,
}

pub fn handler(ctx: Context<ExecuteAttested>, args: ExecuteAttestedArgs) -> Result<()> {
    let account = &mut ctx.accounts.smart_account;
    let registry = &ctx.accounts.relay_registry;

    // 1. Verify the relay is authorized
    require!(
        is_relay_authorized(&args.relay_pubkey, &registry.relays),
        SolaaError::UnauthorizedRelay
    );

    // C5 fix: attest_nonce must equal account.nonce
    require!(args.attest_nonce == account.nonce, SolaaError::NonceMismatch);

    // C6 fix: obj_hash must be SHA256(payload)
    let payload_hash = sha256_hash(&args.payload);
    require!(
        payload_hash.to_bytes() == args.obj_hash,
        SolaaError::PayloadHashMismatch
    );

    // 2. Verify the attestation signature via Ed25519 instruction introspection
    let valid = verify_attestation(
        &ctx.accounts.instructions,
        &args.signature,
        &args.relay_pubkey,
        &args.obj_hash,
        account.domain,
        args.attest_nonce,
    )?;
    require!(valid, SolaaError::InvalidAttestation);

    // 3. Bump nonce
    account.nonce = account.nonce
        .checked_add(1)
        .ok_or(SolaaError::ArithmeticOverflow)?;

    msg!("AR-ACE attested execute: relay verified, nonce={}", account.nonce);
    msg!("  relay_pubkey: {:?}", &args.relay_pubkey[..8]);
    msg!("  payload_len={}", args.payload.len());

    Ok(())
}
